name: .NET

on: ["push", "pull_request"]

jobs:
    build:
        runs-on: windows-latest

        strategy:
            matrix:
                configuration: [Release, Debug]

        steps:
            - uses: actions/checkout@v2

            - name: Setup MSBuild.exe
              uses: microsoft/setup-msbuild@v1.0.3

            - name: Use NuGet 5.2.0
              uses: nuget/setup-nuget@v1

            - name: Restore NuGet Packages
              run: msbuild './StudentInformationSheet/StudentInformationSheet.sln' /p:configuration=${{ matrix.configuration }} /t:restore

            - name: Build Solution
              run: msbuild './StudentInformationSheet/StudentInformationSheet.sln' /p:configuration=${{ matrix.configuration }}
