name: Build WinForms App

on: [push]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v1
              name: Checkout Code

            - name: Setup MSBuild
              uses: warrenbuckley/Setup-MSBuild@v1

            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1.0.2

            - name: Restore NuGet Packages
              run: nuget restore ./StudentInformationSheet/StudentInformationSheet.sln

            - name: Build and Publish Web App
              run: msbuild ./StudentInformationSheet/StudentInformationSheet.sln /p:Configuration=Release /p:PublishSingleFile=true

            - name: Upload Artifact
              uses: actions/upload-artifact@v1.0.0
              with:
                  name: StudentInformationSheet win-x64
                  path: ./StudentInformationSheet/bin/Release/Publish
